[theme]
base="light"
primaryColor="#00fff9"
secondaryBackgroundColor="#F2FFFF"
textColor="#333333"
font="serif"

[global]
layout = "wide"
hideStreamlitFooter = true

[runner]
toolbarMode = "minimal"
