[theme]
base="light"
primaryColor="#00fff9"
secondaryBackgroundColor="#F2FFFF"
textColor="0d0d0d"
font="serif"

[global]
layout = "wide"
hideStreamlitFooter = true

[runner]
toolbarMode = "minimal"
