[theme]

primaryColor = "#3498db"
backgroundColor = "#f0f8ff"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"
font = "sans serif"

[global]
layout = "wide"
hideStreamlitFooter = true

[runner]
toolbarMode = "minimal"
