[theme]
primaryColor="#b2ffff"
backgroundColor="#080808"
secondaryBackgroundColor="#1a1110"
textColor="#f0ffff"
font = "serif"

[global]
layout = "wide"
hideStreamlitFooter = true

[runner]
toolbarMode = "minimal"
