[theme]
base="light"
primaryColor="#00fff9"
secondaryBackgroundColor="#F2FFFF"
textColor="#2F2F2F"
font="monospace"

[global]
layout = "wide"
hideStreamlitFooter = true

[runner]
toolbarMode = "minimal"
