[theme]
primaryColor="#b2ffff"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0ffff"
textColor="#252525"
font = "serif"

[global]
layout = "wide"
hideStreamlitFooter = true

[runner]
toolbarMode = "minimal"
